# This is a basic workflow to help you get started with Actions

name: Publish packages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: git config email
        run: git config --local user.email rushbot@users.noreply.github.com
      - name: git config name
        run: git config --local user.name Rushbot

      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
        
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
        
      - name: Rush Rebuild
        run: node common/scripts/install-run-rush.js rebuild
        
      - name: Rush Publish
        run: node common/scripts/install-run-rush.js publish --publish --apply --target-branch master --npm-auth-token ${{ secrets.NPM_AUTH_TOKEN }}


